export enum TicketStatus {
  Open = 0,
  Pending = 1,
  Closed = 2
}
export enum TicketTypes {
  Support = 0, // generated by anybody from support page
  Season = 1, // generated for season related query by admins
  Profile = 2, // generated for profile-related query by users
}

export const TicketTypeMapping = {
  [TicketTypes.Support]: 'Support Section',
  [TicketTypes.Season]: 'Season related query',
  [TicketTypes.Profile]: 'Profile Deactivation',
}

export interface ISupportTicket {
  title: string;
  date: number;
  status: TicketStatus;
  type: TicketTypes;
  description?: string;
  byUID?: string;
  id?: string
}

export interface IContactDetails {
  name: string;
  email: string;
  phone_no?: string;
}
