export const SUCCESS = 'success';
export const FAILURE = 'failure';
export const LOADING = 'loading';
export const HOME = 'home';
export const PAGE_VIEWS_MAIN = {
  LANDING_PAGE: 'LANDING_PAGE',
  PLAY_PAGE: 'PLAY_PAGE',
  FREESTYLE_PAGE: 'FREESTYLE_PAGE',
  SUPPORT_PAGE: 'SUPPORT_PAGE',
  FAQ_PAGE: 'FAQ_PAGE',
  ACADEMIES_PAGE: 'ACADEMIES_PAGE',
  EQUIPMENT_PAGE: 'EQUIPMENT_PAGE',
  ABOUT_PAGE: 'LANDING_PAGE',
  TERMS_PAGE: 'LANDING_PAGE',
  PRIVACY_PAGE: 'LANDING_PAGE',
};
